sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7"
  - "8"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - ng build && ng serve
deploy:
  provider: heroku
  api_key:
    secure: "00e6c1b3-ed8b-4c79-aa36-64a643bc4c00"
  app:
    master: shoppu
notifications:
  email:
    recipients:
      - yosoyvilla@gmail.com
    on_success: never # default: change
    on_failure: always # default: always